export const LOAD_DATASOURCES_REQUEST = 'LOAD_DATASOURCES_REQUEST';
export const LOAD_DATASOURCES_SUCCESS = 'LOAD_DATASOURCES_SUCCESS';
export const LOAD_DATASOURCES_FAILURE = 'LOAD_DATASOURCES_FAILURE';

export const CONNECT_DATASOURCE_REQUEST = 'CONNECT_DATASOURCE_REQUEST';
export const CONNECT_DATASOURCE_SUCCESS = 'CONNECT_DATASOURCE_SUCCESS';
export const CONNECT_DATASOURCE_FAILURE = 'CONNECT_DATASOURCE_FAILURE';
