export const LOAD_PROFILE_REQUEST = 'LOAD_PROFILE_REQUEST';
export const LOAD_PROFILE_SUCCESS = 'LOAD_PROFILE_SUCCESS';
export const LOAD_PROFILE_FAILURE = 'LOAD_PROFILE_FAILURE';

export const PROFILE_STATUS_GUEST = 1;
export const PROFILE_STATUS_FREEMIUM = 2;
export const PROFILE_STATUS_SCREENING = 3;
export const PROFILE_STATUS_SUBSCRIPTION = 4;
