export const LOAD_REPORTS_REQUEST = 'LOAD_REPORTS_REQUEST';
export const LOAD_REPORTS_SUCCESS = 'LOAD_REPORTS_SUCCESS';
export const LOAD_REPORTS_FAILURE = 'LOAD_REPORTS_FAILURE';
export const CHANGE_REPORTS_SORT = 'CHANGE_REPORTS_SORT';

export const REPORTS_SORT_ASC = 'ASC';
export const REPORTS_SORT_DESC = 'DESC';
